rust_arch:
  - x86_64-unknown-linux-gnu       # [linux64]
  - s390x-unknown-linux-gnu        # [s390x]
  - aarch64-unknown-linux-gnu      # [aarch64]
  - powerpc64le-unknown-linux-gnu  # [ppc64le]
  - x86_64-apple-darwin            # [osx and x86_64]
  - aarch64-apple-darwin           # [osx and arm64]
